puts "🌱 Seeding enneadrink data..."

water = Enneadrink.create(drink: "water", number: 1, title: "the good", emoji: "🌊",
    about: "Waters are attracted to and value goodness.
    They believe life is about doing your best, setting high standards and goals and living up to them. Many Waters report growing up in families with high standards and the pressure to perform, often being criticized for their mistakes. As a result, they developed a fear of failure and an incessant need to be perfect and good enough, unconsciously seeking to earn the love and acceptance of their caregivers. They become model children who are motivated to ‘be good,’ ‘try harder’ and ‘get it right.’ As adults, Waters are sometimes described as obsessive compulsive, always trying to perfect and make things better. There is always room for improvement for Waters. They are critical toward others’ mistakes and especially critical toward their own. Their drive for perfection often leads them to reform what is broken and can be a blessing. However, it can also be a burden, leading to a deep sense of anger and guilt.",
    strengths: "Waters live with conviction, are bold and courageous. 
    Healthy Waters are willing to take a stand and sacrifice themselves for what’s right, and keep the mission moving forward; they are sensible, responsible, ethical, self- disciplined, just, fair, tolerant of failure—both theirs and others—and accepting of their limits and losses.",
    weaknesses: "For Waters, the besetting struggle is anger. 
    The underlying emotion Waters are trying to conquer is guilt. Waters often carry a suppressed anger because nothing is ever good enough— including and especially themselves. This anger is driven by an exaggerated sense of guilt and a feeling of not measuring up, which leads Waters to be very hard on themselves. Few casual observers would suspect how much Waters are suffering from the attacks of their Inner Critic. This is not only how Waters tend to relate to themselves, but to others, through performance and criticism."
)

tea = Enneadrink.create(drink: "tea", number: 2, title: "the loving", emoji: "🧋",
    about: "Teas see the world in terms of loving and serving people.
    Life is about being generous and meeting the needs of others. It’s possible that Teas grew up in an environment where they had to step up at a young age and learn how to take care of themselves and others emotionally and/or physically. They may have had to provide emotional support for their parents and siblings, sometimes becoming the parent in the family. This means that Teas had to grow up fast. As a result, Teas cultivated a gift for empathy and moving toward others in love and service. However, the dark side of Teas is a desperate need to be needed. This is the essence of their inner battle with shame and pride.",
    strengths: "Teas are thoughtful, caring, and empathetic. 
    Healthy Teas are in touch with their own emotional and spiritual needs and are willing to be vulnerable before others. They express appreciation, generosity, humility, affection, encouragement, compassion, and others-orientedness.",
    weaknesses: "Teas battle shame and a sense of worthlessness if they aren’t needed by others. 
    Ironically, this leads to a form of pride that unconsciously motivates Teas in the sense that their service of others can be motivated by their own self-interest and need for approval. This can lead to people-pleasing, over-attachment to people, and the fear of man. Unhealthy Teas also deny their own needs. They are energized by meeting others’ needs but fear having the tables turned since it compromises their survival strategy of being the caregiver."
)

sparkling = Enneadrink.create(drink: "sparkling water", number: 3, title: "the effective", emoji: "✨",
    about: "Sparkling Waters see the world in terms of accomplishments and achievements. 
    Life is about being productive, getting things done, accomplishing goals, and winning. Above all, Sparkling Waters want to be the best at whatever they do, basically doing whatever it takes to shine. It’s possible that Sparkling Waters grew up in an environment where there was a high value on looking presentable and put together or maybe there was an unusual emphasis on excellence and being the best. There was a greater emphasis on how you looked and how you performed and less emphasis on who you were. As a result, Sparkling Waters learned to use popularity and the image of success as a way to feel loved and accepted rather than receiving love through vulnerability and trust. Sparkling Waters are driven by 3 C’s: Competency, Comparison, and Competition. This can lead Sparkling Waters to accomplish great things, but it can also lead to self-promotion and exaggerated feelings of shame.",
    strengths: "Sparkling Waters are effective, competent, and adaptable. 
    Healthy Sparkling Waters are driven by love instead of shame. They are authentic, gracious, humble, hard-working yet restful, tolerant of their failures, accepting of their limits and losses, and interested in others.",
    weaknesses: "For Sparkling Waters, the besetting struggle is deceit or projecting a false image. 
    The underlying emotion they are trying to resolve is shame. Whereas Waters desire to be perfect, Sparkling Waters desire to look perfect. Unhealthy Sparkling Waters relate through performance and perception, striving to be or at least be seen as good enough. The question Sparkling Waters are asking is, 'Who am I if I’m not seen as successful?' Sparkling Waters tend to shine on the outside in whatever they do, while their inner life remains disconnected. Preoccupied with speed and efficiency in accomplishing their goals, Sparkling Waters rarely slow down and press inward to get in touch with their emotions."
)

espresso = Enneadrink.create(drink: "espresso", number: 4, title: "the original", emoji: "🚂",
    about: "Espressos are sometimes called 'the romantics of the Enneadrinks.'
    They see the world in terms of beauty, the arts, and authentic expression. They value being original and unique. Espressos are also very aware of their emotional states. They often express their feelings in dance, music, painting, acting, and literature. Many Espressos report growing up with a sense of loss, and therefore they carry a deep sense that something is always missing. There might have been some form of abandonment or neglect, emotional and/or physical, from their childhood or the loss of someone really important to them. They may have interpreted their experience to mean that something was wrong with them, that they weren’t wanted or weren’t special enough to be noticed. To compensate, Espressos learned to present themselves as unique and extra special, so that others would notice them and affirm their worth.",
    strengths: "Espressos express beauty, creativity, and emotional honesty.
    Healthy Espressos are not only in touch with their own emotions but with the emotional state of others; they are compassionate, empathetic, great listeners, sensitive, impressionable, passionate, romantic, elegant, witty, imaginative, self-expressive, creative, inspired, not self-absorbed or self-pitying, and emotionally strong for themselves and others.",
    weaknesses: "For Espressos, the besetting struggle is envy.
    At some level, Espressos believe they are missing something that other people seem to have. Naturally, this can lead to be envious of others. The driving emotion beneath the surface is shame and a low view of self. Unhealthy Espressos are known to give themselves to a critical, melancholy, depressed, self-loathing spirit. While they don’t like it, they can easily get comfortable in a dark place and wear that for their identity. Their own darkness becomes another means of being different and trying to overcome shame. This is a self-destructive pattern."
)

latte = Enneadrink.create(drink: "latte", number: 5, title: "the wise", emoji: "🌌",
    about: "Lattes see the world in terms of reason, knowledge, learning, and storing up information.
    Life is about having insights, learning about things, and seeing how everything fits together. They tend to be highly innovative and inventive. Many Lattes report growing up in a disruptive, somewhat intrusive environment. It’s possible that they were interrupted a lot and also emotionally and/or physically neglected. As a result, Lattes learned that it was safer to do everything alone, and they created an intellectual world where they could function and feel safe. They live a compartmentalized life, detached from the their emotions. If you ask Lattes what they feel, they will tell you what they think.",
    strengths: "Lattes are ever fascinated with the world. 
    Healthy Lattes are studious, perceptive, pioneering, innovative, focused, observant, curious, insightful, objective, understanding, playful, compassionate, and know how to love others with their information and knowledge rather than hide in it. Because they love to observe, they make wonderful listeners and counselors.",
    weaknesses: "Lattes perceive the world as a dangerous place and battle an underlying emotion of fear. 
    Their besetting sin is greed. This is not a monetary greed; rather, it is the lack of ability to be open and generous with one’s self. The Lattes' defense mechanism is to hide inside their wealth of knowledge and live inside their minds. Lattes are afraid of their feelings, so they hide in their thoughts. They’re afraid of being vulnerable and known, so they withhold their true selves. Unhealthy Lattes can be argumentative, high strung, cynical, reclusive, even nihilistic."
)

lemon = Enneadrink.create(drink: "lemon water", number: 6, title: "the loyal", emoji: "🍋",
    about: "Lemon Waters value being faithful, reliable, prepared, dutiful, responsible, and conscientious.
    Above all, they value safety, security, and stability. Many Lemon Waters report growing up in unstable homes, where the emotional atmosphere was up and down. It’s possible that the authoritative figures in their lives didn’t use their power in a way that made them feel safe. They might have been emotionally unreliable, overly protective, or even abusive. Basically, they were inconsistent in their care. As a result, Lemon Waters struggle to trust authority and learned they need to try to win over the authoritative figures in their life in order to feel protected or oppose them in order to protect themselves.",
    strengths: "Lemon Waters are faithful, steadfast, and loyal. 
    Healthy Lemon Waters are a stabilizing presence. They have the ability to ground people in reality and draw out their emotions. They are faithful, reliable, hard-working, courageous, leaders, self-expressive, vigilant, secure, charming, funny, and affectionate.",
    weaknesses: "The underlying emotion Lemon Waters are trying to overcome is fear. 
    Their besetting struggle is anxiety. They are the most anxious type of all the Enneadrinks. They live in their heads and let their thoughts run away with them. They tend to worry about what they’re going to worry about. It’s not just that they struggle to trust others, but Lemon Waters really struggle to trust themselves. Lemon Waters are plagued with self-doubt. They tirelessly look for some kind of structure to hide in, an environment that will reassure them and make them feel safe and secure and stable. The questions their soul is asking are, Where am I? Am I safe? Unhealthy Lemon Waters are suspicious of others, especially authority."
)

smoothie = Enneadrink.create(drink: "smoothie", number: 7, title: "the joyful", emoji:"🌄",
    about: "Smoothies are all about fun and joy and excitement.
    They are probably the most upbeat, extroverted, outgoing type of the Enneadrinks. They light up a room with their presence. There is a glow and positive energy that emanates from them. Many Smoothies report carrying a deep childhood wound, which they try to avoid at all costs through the pursuit of new experiences, staying active, and entertainment. Their strategy is to repress their traumatic experiences from childhood and paint their life story in positive colors, even when the scenario was anything but beautiful. Appearing to be full of heart, Smoothies actually operate from the head. They carefully think through their lives so that every day will promise as much fun and as little pain as possible.",
    strengths: "Smoothies bring joy and spark into people's lives. 
    Healthy Smoothies are excitable, spontaneous, curious, optimistic, eager, outgoing, adventurous, talkative, appreciative, bountiful, thoughtful, accomplished, versatile, receptive, grateful, passionate, celebratory, and most importantly satisfied, content, and at peace with their circumstances and life.",
    weaknesses: "Smoothies are driven by an underlying fear that goes back to their childhood. 
    Their coping strategy is to have as much entertainment as possible, which is why their besetting struggle is gluttony. Smoothies are prone to constant stimulation and consumption as a way of distracting themselves from an inner anxiety. This is their defense strategy against their emotional pain. They 'gobble up' every experience but are always left hungry for more. Thus, they are always looking for the next thing or the perfect combination of things that will heal them and make them truly happy. They tend to be thrill seekers. Their avoidance of pain and endless hunger for more make them prone to various additions, including chronic anxiety. Unhealthy Smoothies would rather keep relationships on the surface because it would be too painful to know their whole story."
)

juice = Enneadrink.create(drink: "juice", number: 8, title: "the powerful", emoji: "🍊",
    about: "Juices are powerful personalities.
    They have a very intense and commanding presence. Juices endeavor to be strong, independent, straightforward, assertive persons who use their strength and influence to make the world a more just place. Juices see the world in black and white— it’s either the greatest or the worst idea of all time, right or wrong, true or false, friend or enemy. Juices are energized by disagreement and don’t like to admit their faults, for this is a sign of weakness. Many Juices report being taken advantage of or treated unfairly in their childhood. As a result,they learned to develop an image of power and strength, believing weakness to be unacceptable. They learned to dominate lest they be dominated. This is their defense strategy.",
    strengths: "Juices are strong and courageous and take a bold stand against injustice.
    Healthy Juices are big-hearted, merciful, forbearing, leaders, determined, resourceful, pragmatic, honorable, heroic, empowering, generous, initiating, decisive, vulnerable, accepting of their weaknesses, and leading with a limp.",
    weaknesses: "The underlying emotion Juices are trying to conquer is guilt, feeling as though they aren’t good enough. 
    Their survival strategy is to be powerful and take control. This leads to their besetting struggle with lust—the passion for power. They become very angry, confrontational and aggressive and throw their weight around. People can feel dominated, controlled, and belittled by Juices, but rarely do Juices notice how they make others feel. They can be emotional bulldozers."
)

hotcocoa = Enneadrink.create(drink: "hot cocoa", number: 9, title: "the peaceful", emoji: "🍫",
    about: "Hot Cocoas value peace, harmony, unity, and wholeness.
    For a Hot Cocoa, life is about bringing people together and being at peace personally and interpersonally. Hot Cocoas tend to go with the flow and want to avoid rocking the boat, i.e., they don’t want to assert themselves out of a fear of conflict. Many Hot Cocoas recall memories of being overlooked and neglected as a child. Their voice didn’t matter. It’s also reported that many Hot Cocoas grew up in families with unhealthy patterns of dealing with conflict. For some, conflict was pushed down, “swept under the rug,” and avoided at all costs. For others, conflict was processed through anger, verbal, or even physical assault. As a result, Hot Cocoas developed a conflict within themselves, struggling to follow their intuition and be bold.",
    strengths: "Hot Cocoas are peaceful, comforting, and reassuring. 
    Healthy Hot Cocoas are patient, steady, receptive, relaxed, agreeable, comforting, self-aware, dynamic, proactive, healing, natural, imaginative, serene, engaged, and passionate. They make excellent mediators, having the ability to be objective and see all sides of an issue. They are essential to a world of conflict and pain.",
    weaknesses: "For Hot Cocoas, the besetting struggle is sloth- not in terms of physical laziness but relational negligence. 
    Hot Cocoas tend to check out emotionally and relationally. When they’re unhealthy, they will run from all conflict, and their defense strategy is to shut down and withdraw. They will no longer be fully present. They can lose themselves and retreat into inoculating activity, like watching TV, playing games on their phone, checking social media, doing busy work, distracting themselves from their emotional needs and the needs of others. This creates a deep sense of guilt in Hot Cocoas, which is the underlying emotion they are trying to overcome."
)

puts "🌱 Seeding practice data..."

practice101 = Practice.create(enneadrink_id: water.id, title: "Improvement projects", description: "Waters feel useful when they are able to speak into things, reform things, and make things better.")
practice102 = Practice.create(enneadrink_id: water.id, title: "Nature walks", description: "A walk through nature can be a calming and emotionally healing discipline for Waters, quieting their inner anger and reorienting them around goodness and beauty.")
practice103 = Practice.create(enneadrink_id: water.id, title: "Receive love through", description: "Verbal reassurance, sharing work loads, encouragement to have fun and take vacations/breaks.")
practice104 = Practice.create(enneadrink_id: water.id, title: "Give love through", description: "Listen without fixing, embrace reality over idealism.")

# practice103 = Practice.create(enneadrink_id: water.id, title: "Consider: Love arises from our imperfection, from our being imperfect and always in need of the forgiveness.", description: "Uncle Iroh: While it is always best to believe in oneself, a little help from others can be a great blessing.")

practice201 = Practice.create(enneadrink_id: tea.id, title: "Deep, encouraging friendship with one or a few people", description: "Teas tend to be energized by deep friendships and sharing life with others.")
practice202 = Practice.create(enneadrink_id: tea.id, title: "Fasting", description: "The discipline of fasting is good for Teas because it helps ground them in the reality of their own needs.")
practice203 = Practice.create(enneadrink_id: tea.id, title: "Receive love through", description: "Sharing fun times together, validate importance, encouragement to accept help.")
practice204 = Practice.create(enneadrink_id: tea.id, title: "Give love through", description: "Listen without fixing, seek clarity over needs and desires.")

# practice203 = Practice.create(enneadrink_id: tea.id, title: "Consider: I am in need, and that's OK.", description: "Uncle Iroh: I know he doesn't want me around right now, but if he needs me, I'll be there.... Toph: Maybe you should tell him that you need him too.")

practice301 = Practice.create(enneadrink_id: sparkling.id, title: "Fixed-Hour prayer or meditation", description: "Martin Luther is famous for commenting, 'I have so much to do today that I’m going to need to spend three hours in prayer in order to be able to get it all done.' Sparkling Waters need this perspective. The interruption of prayer or meditation reminds Sparkling Waters to be OK with the journey and less focused on the need to feel they've arrived.")
practice302 = Practice.create(enneadrink_id: sparkling.id, title: "Social media fasts", description: "Frequent fasts from social media help Sparkling Waters give up false images and provide more emotional margin to be themselves.")
practice303 = Practice.create(enneadrink_id: sparkling.id, title: "Receive love through", description: "Working together on common goals, acknowledge achievements and successes, encouragement to slow down.")
practice304 = Practice.create(enneadrink_id: sparkling.id, title: "Give love through", description: "Remember that quality not just efficiency matters, understand people require patience and do not push too hard or too fast.")

# practice303 = Practice.create(enneadrink_id: sparkling.id, title: "Consider: Might invisibility be regarded not simply as refuge, but as a condition with its own meaning and power? It is not about retreating from the world but about finding some genuine alternative to a life of perpetual display.", description: "Uncle Iroh: Pride is not the opposite of shame, but its source. True humility is the only antidote to shame.; The best tea tastes delicious whether it comes in a porcelain pot or a tin cup.")

practice401 = Practice.create(enneadrink_id: espresso.id, title: "Thanksgiving", description: "Espressos should avoid focusing only on the negative and practice remembering what they have to be thankful for.")
practice402 = Practice.create(enneadrink_id: espresso.id, title: "Regular meals in community/with others", description: "Fellowship is a necessary rhythm for us all, but especially for Espressos who are prone toward isolation. Espressos need to be with others in order to be drawn out of themselves and toward people.")
practice403 = Practice.create(enneadrink_id: espresso.id, title: "Receive love through", description: "Verbal appreciation, empathy without fixing, encouragement to pursue creative work.")
practice404 = Practice.create(enneadrink_id: espresso.id, title: "Give love through", description: "Express appreciation for others, pay attention to others rather than be drawn to introversion.")
# practice403 = Practice.create(enneadrink_id: espresso.id, title: "Consider: I am the combined effort of everyone I've ever known.", description: "Uncle Iroh: I don't know the answer. Sometimes life is like this dark tunnel. You can't always see the light at the end of the tunnel, but if you just keep moving, you will come to a better place.")

practice501 = Practice.create(enneadrink_id: latte.id, title: "Community service", description: "Lattes are prone to remain inside their heads, in secrecy and introversion. Regular acts of service provide a context for whole-person engagement and transformation.")
practice502 = Practice.create(enneadrink_id: latte.id, title: "Reading books", description: "Reading on various subject matter is a helpful practice for Lattes.")
practice503 = Practice.create(enneadrink_id: latte.id, title: "Receive love through", description: "Room for independence/space/privacy, verbal appreciation, encouragement to share thoughts.")
practice504 = Practice.create(enneadrink_id: latte.id, title: "Give love through", description: "Be emotionally present, be willing to share.")

# practice503 = Practice.create(enneadrink_id: latte.id, title: "Consider: There's bravery in being vulnerable.", description: "Uncle Iroh: It is important to draw wisdom from many different places. If you take it from only one place, it becomes rigid and stale.")

practice601 = Practice.create(enneadrink_id: lemon.id, title: "Memorizing grounding truths", description: "This practice challenges the anxious, busy minds of Lemon Waters. It also provides anchors against over-thinking.")
practice602 = Practice.create(enneadrink_id: lemon.id, title: "Prayer or meditation", description: "This practice encourages Lemon Waters to slow down and have their fears confronted and peacefully cast out.")
practice603 = Practice.create(enneadrink_id: lemon.id, title: "Receive love through", description: "Patient listening, verbal reassurance, encouragement to take risks.")
practice604 = Practice.create(enneadrink_id: lemon.id, title: "Give love through", description: "Trust in the benevolence of others, provide loyalty and stability in relationships, projects, and missions.")

# practice603 = Practice.create(enneadrink_id: lemon.id, title: "Consider: It's OK to trust.", description: "Uncle Iroh: You are stronger and wiser and freer than you have ever been.")

practice701 = Practice.create(enneadrink_id: smoothie.id, title: "Celebration", description: "Smoothies should not feel shame over looking for ways to enjoy life to the fullest. Smoothies will feel alive through engaging with others through a variety of experiences: feasting, laughing, listening to music, watching movies, deep conversation, etc. This will help Smoothies to use these practices as opportunities to open themselves up to others and share their joy and story. The challenge for Smoothies will be to not over-indulge.")
practice702 = Practice.create(enneadrink_id: smoothie.id, title: "Silent solitude", description: "Solitude releases Smoothies from their stage persona, need to perform, and over-dependence on others. Silence allow them to feel whatever they’re trying to avoid beneath the surface and to meet with their inner being and emotional pain.")
practice703 = Practice.create(enneadrink_id: smoothie.id, title: "Receive love through", description: "Doing spontaneous things together, discussing stories and visions, gentle encouragement to face problems and pain.")
practice704 = Practice.create(enneadrink_id: smoothie.id, title: "Give love through", description: "Stay present in difficult circumstances and conversations, pursue commitment to relationships and projects.")

# practice703 = Practice.create(enneadrink_id: smoothie.id, title: "Consider: Let it go.", description: "Uncle Iroh: Good times become good memories, but bad times make good lessons.")

practice801 = Practice.create(enneadrink_id: juice.id, title: "Deep, encouraging friendship with one or a few people", description: "Juices tend to avoid vulnerability and letting others get close out of fear of being controlled by them. To overcome this, Juices need accountability from people they know they can trust. They need a context where they can be known and where they can be weak. If not, Juices will spend their lives hiding their true self behind an image of power.")
practice802 = Practice.create(enneadrink_id: juice.id, title: "Community service", description: "Juices are filled with compassion for the underdog. It’s not enough for them to speak out against injustice. They feel the need to get involved, to stand in the shoes of those they’re trying to help. They have a great capacity for empathy. Showing compassion by stepping in and physically serving the under-resourced is a way of living into their true selves.")
practice803 = Practice.create(enneadrink_id: juice.id, title: "Receive love through", description: "Acknowledge contributions and compassion, standing up for justice together, encouragement to cope with stress through exercise or relaxation.")
practice804 = Practice.create(enneadrink_id: juice.id, title: "Give love through", description: "Carefully gather information and perspective before coming to conclusions, slow down and be willing to wait rather than immediately act with force.")

# practice803 = Practice.create(enneadrink_id: juice.id, title: "Consider: Gentleness is not weakness.", description: "Uncle Iroh: Sometimes, the best way to solve your own problems is to help someone else.")

practice901 = Practice.create(enneadrink_id: hotcocoa.id, title: "Nature retreats", description: "Walking trails, hiking, climbing, biking, jogging, strolling the park or beach return Hot Cocoas to a sense of peace and calm. Nature reminds them that, though we live in a world of chaos, there is hope for peace and order.")
practice902 = Practice.create(enneadrink_id: hotcocoa.id, title: "Fixed-Hour prayer or meditation", description: "Stopping routinely to pray or meditate is good for Hot Cocoas because it re-centers them. It is a way of calming down and remembering what is most urgent and important. This practice also helps to form diligence, steadfastness, faithfulness, and action.")
practice903 = Practice.create(enneadrink_id: hotcocoa.id, title: "Receive love through", description: "Patience/space to finish talking, verbal appreciation, encouragement to express frustrations or grievances.")
practice904 = Practice.create(enneadrink_id: hotcocoa.id, title: "Give love through", description: "Bring harmony in times of conflict, make decisions or name and share thoughts and feelings.")
# practice903 = Practice.create(enneadrink_id: hotcocoa.id, title: "Consider: Your presence and opinion matters.", description: "Uncle Iroh: Perfection and power are overrated. I think you are very wise to choose happiness and love.")

puts "🌱 Seeding health data..."

health101 = Health.create(enneadrink_id: water.id, level: 1, description: "Become extraordinarily wise and discerning. By accepting what is, they become transcendentally realistic, knowing the best action to take in each moment. Humane, inspiring, and hopeful; the truth will be heard.")
health102 = Health.create(enneadrink_id: water.id, level: 2, description: "Conscientious with strong personal convictions, they have an intense sense of right and wrong, personal religious and moral values. Wish to be rational, reasonable, self-disciplined, mature, moderate in all things.")
health103 = Health.create(enneadrink_id: water.id, level: 3, description: "Extremely principled, always want to be fair, objective, and ethical: truth and justice primary values. Sense of responsibility, personal integrity, and of having a higher purpose often make them teachers and witnesses to the truth.")
health104 = Health.create(enneadrink_id: water.id, level: 4, description: "Dissatisfied with reality, they become high-minded idealists, feeling that it is up to them to improve everything: crusaders, advocates, critics. Into 'causes' and explaining to others how things 'ought' to be.")
health105 = Health.create(enneadrink_id: water.id, level: 5, description: "Afraid of making a mistake, everything must be consistent with their ideals. Become orderly and well- organized, but impersonal, puritanical, emotionally constricted, rigidly keeping their feelings and impulses in check. Often workaholics—'obsessive-compulsive,' punctual, pedantic, and fastidious.")
health106 = Health.create(enneadrink_id: water.id, level: 6, description: "Highly critical both of self and others: picky, judgmental, perfectionistic. Very opinionated about everything: correcting people and badgering them to 'do the right thing'—as they see it. Impatient, never satisfied with anything unless it is done according to their prescriptions. Moralizing, scolding, abrasive, and indignantly angry.")
health107 = Health.create(enneadrink_id: water.id, level: 7, description: "Can be highly dogmatic, self-righteous, intolerant, and inflexible. Begin dealing in absolutes; they alone know 'The Truth.' Everyone else is wrong; very severe in judgments, while rationalizing own actions.")
health108 = Health.create(enneadrink_id: water.id, level: 8, description: "Become obsessive about imperfection and the wrongdoing of others, although they may fall into contradictory actions, hypocritically doing the opposite of what they preach.")
health109 = Health.create(enneadrink_id: water.id, level: 9, description: "Become condemnatory toward others, punitive and cruel to rid themselves of wrongdoers. Severe depressions, nervous breakdowns, and suicide attempts are likely. Generally corresponds to the Obsessive-Compulsive and Depressive personality disorders.")

health201 = Health.create(enneadrink_id: tea.id, level: 1, description: "Become deeply unselfish, humble, and altruistic, giving unconditional love to self and others. Feel it is a privilege to be in the lives of others.")
health202 = Health.create(enneadrink_id: tea.id, level: 2, description: "Empathetic, compassionate, feeling for others. Caring and concerned about their needs. Thoughtful, warm- hearted, forgiving, and sincere.")
health203 = Health.create(enneadrink_id: tea.id, level: 3, description: "Encouraging and appreciative, able to see the good in others. Service is important, but takes care of self too; nurturing, generous, and giving—a truly loving person.")
health204 = Health.create(enneadrink_id: tea.id, level: 4, description: "Want to be closer to others, so start 'people pleasing,' becoming overly friendly, emotionally demonstrative, and full of 'good intentions' about everything. Give seductive attention: approval, 'strokes,' flattery. Love is their supreme value, and they talk about it constantly.")
health205 = Health.create(enneadrink_id: tea.id, level: 5, description: "Become overly intimate and intrusive; they need to be needed, so they hover, meddle, and control in the name of love. Want others to depend on them; give, but expect a return. Send double messages. Enveloping and possessive, the codependent, self-sacrificial person who cannot do enough for others—wearing themselves out for everyone, creating needs for themselves to fulfill.")
health206 = Health.create(enneadrink_id: tea.id, level: 6, description: "Increasingly self-important and self-satisfied, feel they are indispensable, although they overrate their efforts in others’ behalf. Hypochondria, becoming a 'martyr' for others. Overbearing, patronizing, presumptuous.")
health207 = Health.create(enneadrink_id: tea.id, level: 7, description: "Can be manipulative and self-serving, instilling guilt by telling others how much they owe them and make them suffer. Abuse food and medication to 'stuff feelings' and get sympathy. Undermine people, making belittling, disparaging remarks. Extremely self-deceptive about their motives and how aggressive and/or selfish their behavior is.")
health208 = Health.create(enneadrink_id: tea.id, level: 8, description: "Domineering and coercive; feel entitled to get anything they want from others with the repayment of old debts, money, sexual favors.")
health209 = Health.create(enneadrink_id: tea.id, level: 9, description: "Able to excuse and rationalize what they do since they feel abused and victimized by others and are bitterly resentful and angry. Somatization of their aggressions results in chronic health problems as they vindicate themselves by 'falling apart' and burdening others. Generally corresponds to the Histrionic Personality Disorder and Factitious Disorder.")

health301 = Health.create(enneadrink_id: sparkling.id, level: 1, description: "Self-accepting, inner-directed, and authentic, everything they seem to be. Modest and charitable, self-deprecatory humor, and a fullness of heart emerge. Gentle and benevolent.")
health302 = Health.create(enneadrink_id: sparkling.id, level: 2, description: "Self-assured, energetic, and competent with high self-esteem: they believe in themselves and their own value. Adaptable, desirable, charming, and gracious.")
health303 = Health.create(enneadrink_id: sparkling.id, level: 3, description: "Ambitious to improve themselves, to be 'the best they can be' —often become outstanding, a human ideal, embodying widely admired cultural qualities. Highly effective; others are motivated to be like them in some positive way.")
health304 = Health.create(enneadrink_id: sparkling.id, level: 4, description: "Highly concerned with their performance, doing their job well, constantly driving self to achieve goals as if self-worth depends on it. Terrified of failure. Compare self with others in search for status and success. Become careerists, social climbers, invested in exclusivity and being the 'best.'")
health305 = Health.create(enneadrink_id: sparkling.id, level: 5, description: "Become image-conscious, highly concerned with how they are perceived. Begin to package themselves according to the expectations of others and what they need to do to be successful. Pragmatic and efficient, but also premeditated, losing touch with their own feelings beneath a smooth facade. Problems with intimacy, credibility, and 'phoniness' emerge.")
health306 = Health.create(enneadrink_id: sparkling.id, level: 6, description: "Want to impress others with their superiority; constantly promoting themselves, making themselves sound better than they really are. Narcissistic, with grandiose, inflated notions about themselves and their talents. Exhibitionistic and seductive, as if saying, 'Look at me!' Arrogance and contempt for others is a defense against feeling jealous of others and their success.")
health307 = Health.create(enneadrink_id: sparkling.id, level: 7, description: "Fearing failure and humiliation, they can be exploitative and opportunistic, covetous of the success of others, and willing to do 'whatever it takes' to preserve the illusion of their superiority.")
health308 = Health.create(enneadrink_id: sparkling.id, level: 8, description: "Devious and deceptive so that their mistakes and wrongdoings will not be exposed. Untrustworthy, maliciously betraying or sabotaging people to triumph over them. Delusionally jealous of others.")
health309 = Health.create(enneadrink_id: sparkling.id, level: 9, description: "Become vindictive, attempting to ruin others’ happiness. Relentless, obsessive about destroying whatever reminds them of their own shortcomings and failures. Psychopathic behavior. Generally corresponds to the Narcissistic Personality Disorder.")

health401 = Health.create(enneadrink_id: espresso.id, level: 1, description: "Profoundly creative, expressing the personal and the universal, possibly in a work of art. Inspired, self-renewing, and regenerating. Able to transform all their experiences into something valuable; self-creative.")
health402 = Health.create(enneadrink_id: espresso.id, level: 2, description: "Self-aware, introspective, on the 'search for self,' aware of feelings and inner impulses. Sensitive and intuitive both to self and others; gentle, tactful, compassionate.")
health403 = Health.create(enneadrink_id: espresso.id, level: 3, description: "Highly personal, individualistic, 'true to self.' Self-revealing, emotionally honest, humane. Ironic view of self and life; can be serious and funny, vulnerable and emotionally strong.")
health404 = Health.create(enneadrink_id: espresso.id, level: 4, description: "Take an artistic, romantic orientation to life, creating a beautiful, aesthetic environment to cultivate and prolong personal feelings. Heighten reality through fantasy, passionate feelings, and the imagination.")
health405 = Health.create(enneadrink_id: espresso.id, level: 5, description: "To stay in touch with feelings, they interiorize everything, taking everything personally, but become self- absorbed and introverted, moody and hypersensitive, shy and self-conscious, unable to be spontaneous or to 'get out of themselves.' Stay withdrawn to protect their self-image and to buy time to sort out feelings.")
health406 = Health.create(enneadrink_id: espresso.id, level: 6, description: "Gradually think that they are different from others and feel that they are exempt from living as everyone else does. They become melancholy dreamers, disdainful, decadent, and sensual, living in a fantasy world. Self-pity and envy of others leads to self-indulgence and to becoming increasingly impractical, unproductive, effete, and precious.")
health407 = Health.create(enneadrink_id: espresso.id, level: 7, description: "When dreams fail, become self-inhibiting and angry at self, depressed and alienated from self and others, blocked and emotionally paralyzed. Ashamed of self, fatigued, and unable to function.")
health408 = Health.create(enneadrink_id: espresso.id, level: 8, description: "Tormented by delusional self-contempt, self-reproaches, self-hatred, and morbid thoughts; everything is a source of torment. Blaming others, they drive away anyone who tries to help them.")
health409 = Health.create(enneadrink_id: espresso.id, level: 9, description: "Despairing, feel hopeless, and become self-destructive, possibly abusing alcohol or drugs to escape. In the extreme: emotional breakdown or suicide is likely. Generally corresponds to the Avoidant, Depressive, and Narcissistic personality disorders.")

health501 = Health.create(enneadrink_id: latte.id, level: 1, description: "Become visionaries, broadly comprehending the world while penetrating it profoundly. Open-minded, take things in whole, in their true context. Make pioneering discoveries and find entirely new ways of doing and perceiving things.")
health502 = Health.create(enneadrink_id: latte.id, level: 2, description: "Observe everything with extraordinary perceptiveness and insight. Most mentally alert, curious, searching intelligence; nothing escapes their notice. Foresight and prediction. Able to concentrate; become engrossed in what has caught their attention.")
health503 = Health.create(enneadrink_id: latte.id, level: 3, description: "Attain skillful mastery of whatever interests them. Excited by knowledge; often become expert in some field. Innovative and inventive, producing extremely valuable, original works. Highly independent, idiosyncratic, and whimsical.")
health504 = Health.create(enneadrink_id: latte.id, level: 4, description: "Begin conceptualizing and fine-tuning everything before acting—working things out in their minds: model- building, preparing, practicing, and gathering more resources. Studious, acquiring technique. Become specialized and 'intellectual,' often challenging accepted ways of doing things.")
health505 = Health.create(enneadrink_id: latte.id, level: 5, description: "Increasingly detached as they become involved with complicated ideas or imaginary worlds. Become preoccupied with their visions and interpretations rather than reality. Are fascinated by off-beat, esoteric subjects, even those involving dark and disturbing elements. Detached from the practical world, a 'disembodied mind,' although high- strung and intense.")
health506 = Health.create(enneadrink_id: latte.id, level: 6, description: "Begin to take an antagonistic stance toward anything that would interfere with their inner world and personal vision. Become provocative and abrasive, with intentionally extreme and radical views. Cynical and argumentative.")
health507 = Health.create(enneadrink_id: latte.id, level: 7, description: "Become reclusive and isolated from reality, eccentric and nihilistic. Highly unstable and fearful of aggressions; they reject and repulse others and all social attachments.")
health508 = Health.create(enneadrink_id: latte.id, level: 8, description: "Get obsessed yet frightened by their threatening ideas, becoming horrified, delirious, and prey to gross distortions and phobias.")
health509 = Health.create(enneadrink_id: latte.id, level: 9, description: "Seeking oblivion, they may commit suicide or have a psychotic break with reality. Deranged, explosively self- destructive, with schizophrenic overtones. Generally corresponds to the Schizoid Avoidant and Schizotypal personality disorders.")

health601 = Health.create(enneadrink_id: lemon.id, level: 1, description: "Become self-affirming, trusting of self and others, independent yet symbiotically interdependent and cooperative as an equal. Belief in self leads to true courage, positive thinking, leadership, and rich self-expression.")
health602 = Health.create(enneadrink_id: lemon.id, level: 2, description: "Able to elicit strong emotional responses from others; very appealing, endearing, lovable, affectionate. Trust important; bonding with others, forming permanent relationships and alliances.")
health603 = Health.create(enneadrink_id: lemon.id, level: 3, description: "Dedicated to individuals and movements in which they deeply believe. Community builders; responsible, reliable, trustworthy. Hard-working and persevering, sacrificing for others, they create stability and security in their world, bringing a cooperative spirit.")
health604 = Health.create(enneadrink_id: lemon.id, level: 4, description: "Start investing their time and energy into whatever they believe will be safe and stable. Organizing and structuring, they look to alliances and authorities for security and continuity. Constantly vigilant, anticipating problems.")
health605 = Health.create(enneadrink_id: lemon.id, level: 5, description: "To resist having more demands made on them, they react against others passive-aggressively. Become evasive, indecisive, cautious, procrastinating, and ambivalent. Are highly reactive, anxious, and negative, giving contradictory, 'mixed signals.' Internal confusion makes them react unpredictably.")
health606 = Health.create(enneadrink_id: lemon.id, level: 6, description: "To compensate for insecurities, they become sarcastic and belligerent, blaming others for their problems, taking a tough stance toward 'outsiders.' Highly reactive and defensive, dividing people into friends and enemies, while looking for threats to their own security. Authoritarian while fearful of authority, highly suspicious, yet, conspiratorial and fear- instilling to silence their own fears.")
health607 = Health.create(enneadrink_id: lemon.id, level: 7, description: "Fearing that they have ruined their security, they become panicky, volatile, and self-disparaging with acute inferiority feelings. Seeing themselves as defenseless, they seek out a stronger authority or belief to resolve all problems. Highly divisive, disparaging and berating others.")
health608 = Health.create(enneadrink_id: lemon.id, level: 8, description: "Feeling persecuted, that others are 'out to get them,' they lash-out and act irrationally, bringing about what they fear. Fanaticism, violence.")
health609 = Health.create(enneadrink_id: lemon.id, level: 9, description: "Hysterical and seeking to escape punishment, they become self-destructive and suicidal. Alcoholism, drug overdoses, 'skid row,' self-abasing behavior. Generally corresponds to the Passive-Aggressive and Paranoid personality disorders.")

health701 = Health.create(enneadrink_id: smoothie.id, level: 1, description: "Assimilate experiences in depth, making them deeply grateful and appreciative for what they have. Become awed by the simple wonders of life; joyous and ecstatic. Intimations of spiritual reality, of the boundless goodness of life.")
health702 = Health.create(enneadrink_id: smoothie.id, level: 2, description: "Highly responsive, excitable, enthusiastic about sensation and experience. Most extroverted type: stimuli bring immediate responses—they find everything invigorating. Lively, vivacious, eager, spontaneous, resilient, cheerful.")
health703 = Health.create(enneadrink_id: smoothie.id, level: 3, description: "Easily become accomplished achievers, generalists who do many different things well; multi-talented. Practical, productive, usually prolific, cross-fertilizing areas of interest.")
health704 = Health.create(enneadrink_id: smoothie.id, level: 4, description: "As restlessness increases, want to have more options and choices available to them. Become adventurous and worldly wise, but less focused, constantly seeking new things and experiences; the sophisticate, connoisseur, and consumer. Money, variety, keeping up with the latest trends are seen as important.")
health705 = Health.create(enneadrink_id: smoothie.id, level: 5, description: "Unable to discriminate what they really need, become hyperactive, unable to say 'no' to themselves, throwing self into constant activity. Uninhibited, doing and saying whatever comes to mind: storytelling, flamboyant exaggerations, witty wise-cracking, performing. Fear being bored; in perpetual motion, but do too many things—many ideas but little follow-through.")
health706 = Health.create(enneadrink_id: smoothie.id, level: 6, description: "Get into conspicuous consumption and all forms of excess. Self-centered, materialistic, and greedy, never feeling that they have enough. Demanding and pushy, yet unsatisfied and jaded. Addictive, hardened, and insensitive.")
health707 = Health.create(enneadrink_id: smoothie.id, level: 7, description: "Desperate to quell their anxieties, can be impulsive and infantile: do not know when to stop. Addictions and excess take their toll; debauched, depraved, dissipated escapists, offensive and abusive.")
health708 = Health.create(enneadrink_id: smoothie.id, level: 8, description: "In flight from self, acting out impulses rather than dealing with anxiety or frustrations; go out of control, into erratic mood swings, and compulsive actions- manias.")
health709 = Health.create(enneadrink_id: smoothie.id, level: 9, description: "Finally, their energy and health is completely spent: become claustrophobic and panic-stricken. Often give up on themselves and life; deep depression and despair, self-destructive overdoses, impulsive suicide. Generally corresponds to the Bipolar disorder and Histrionic personality disorder.")

health801 = Health.create(enneadrink_id: juice.id, level: 1, description: "Become self-restrained and magnanimous, merciful and forbearing, mastering self through their self-surrender to a higher authority. Courageous, willing to put self in serious jeopardy to achieve their vision and have a lasting influence. May achieve true heroism and historical greatness.")
health802 = Health.create(enneadrink_id: juice.id, level: 2, description: "Self-assertive, self-confident, and strong; have learned to stand up for what they need and want. A resourceful, 'can do' attitude and passionate inner drive.")
health803 = Health.create(enneadrink_id: juice.id, level: 3, description: "Decisive, authoritative, and commanding; the natural leader others look up to. Take initiative, make things happen; champion people, provider, protective, and honorable, carrying others with their strength.")
health804 = Health.create(enneadrink_id: juice.id, level: 4, description: "Self-sufficiency, financial independence, and having enough resources are important concern; become enterprising, pragmatic, 'rugged individualists,' wheeler-dealers. Risk-taking, hardworking, denying own emotional needs.")
health805 = Health.create(enneadrink_id: juice.id, level: 5, description: "Begin to dominate their environment, including others; want to feel that others are behind them, supporting their efforts. Swaggering, boastful, forceful, and expansive: the 'boss' whose word is law. Proud, egocentric, want to impose their will and vision on everything, not seeing others as equals or treating them with respect.")
health806 = Health.create(enneadrink_id: juice.id, level: 6, description: "Become highly combative and intimidating to get their way; confrontational, belligerent, creating adversarial relationships. Everything a test of wills, and they will not back down. Use threats and reprisals to get obedience from others, to keep others off balance and insecure. However, unjust treatment makes others fear and resent them, possibly also band together against them.")
health807 = Health.create(enneadrink_id: juice.id, level: 7, description: "Defying any attempt to control them, become completely ruthless, dictatorial, 'might makes right.' The criminal and outlaw, renegade, and con-artist. Hard-hearted, immoral, and potentially violent.")
health808 = Health.create(enneadrink_id: juice.id, level: 8, description: "Develop delusional ideas about their power, invincibility, and ability to prevail; megalomania, feeling omnipotent, invulnerable. Recklessly over-extending self.")
health809 = Health.create(enneadrink_id: juice.id, level: 9, description: "If they get in danger, they may brutally destroy everything that has not conformed to their will rather than surrender to anyone else. Vengeful, barbaric, murderous. Sociopathic tendencies. Generally corresponds to the Antisocial Personality Disorder.")

health901 = Health.create(enneadrink_id: hotcocoa.id, level: 1, description: "Become self-possessed, feeling autonomous and fulfilled: have great equanimity and contentment because they are present to themselves. Paradoxically, at one with self, and thus able to form more profound relationships. Intensely alive, fully connected to self and others.")
health902 = Health.create(enneadrink_id: hotcocoa.id, level: 2, description: "Deeply receptive, accepting, unselfconscious, emotionally stable, and serene. Trusting of self and others, at ease with self and life, innocent and simple. Patient, unpretentious, good-natured, genuinely nice people.")
health903 = Health.create(enneadrink_id: hotcocoa.id, level: 3, description: "Optimistic, reassuring, supportive; have a healing and calming influence—harmonizing groups, bringing people together. A good mediator, synthesizer, and communicator.")
health904 = Health.create(enneadrink_id: hotcocoa.id, level: 4, description: "Fear conflicts, so become self-effacing and accommodating, idealizing others and 'going along' with their wishes, saying 'yes' to things they do not really want to do. Fall into conventional roles and expectations. Use philosophies and stock sayings to deflect others.")
health905 = Health.create(enneadrink_id: hotcocoa.id, level: 5, description: "Active, but disengaged, unreflective, and inattentive. Do not want to be affected, so become unresponsive and complacent, walking away from problems, and 'sweeping them under the rug.' Thinking becomes hazy and ruminative, mostly comforting fantasies, as they begin to 'tune out' reality, becoming oblivious. Emotionally indolent, unwillingness to exert self or to focus on problems, indifference.")
health906 = Health.create(enneadrink_id: hotcocoa.id, level: 6, description: "Begin to minimize problems, to appease others and to have 'peace at any price.' Stubborn, fatalistic, and resigned, as if nothing could be done to change anything. Into wishful thinking and magical solutions. Others frustrated and angry by their procrastination and unresponsiveness.")
health907 = Health.create(enneadrink_id: hotcocoa.id, level: 7, description: "Can be highly repressed, undeveloped, and ineffectual. Feel incapable of facing problems; become obstinate, dissociating self from all conflicts. Neglectful and dangerous to others.")
health908 = Health.create(enneadrink_id: hotcocoa.id, level: 8, description: "Wanting to block out of awareness anything that could affect them, they dissociate so much that they eventually cannot function; numb, depersonalized.")
health909 = Health.create(enneadrink_id: hotcocoa.id, level: 9, description: "They finally become severely disoriented and catatonic, abandoning themselves, turning into shattered shells. Multiple personalities possible. Generally corresponds to the Schizoid and Dependent personality disorders.")
